### PR TITLE
get ready for grunt v1.0.0

### PR DESCRIPTION
**Pull request by steveoh**
Fixes https://github.com/gruntjs/grunt-docs/blob/master/Blog-2016-02-11-Grunt-1.0.0-rc1-released.md#peer-dependencies

### CODE REVIEW

**Comment by ericclemmons** [comment]
@steveoh How'd you like to take over this project?  I don't use Grunt anymore.

**Comment by steveoh** [comment]
I'm unsure. We just fooled around the other day using this to hide sauce credentials in travis. I can certainly help out but I don't have a vision of any future.

**Comment by steveoh** [comment]
@ericclemmons you can make me a collaborator if you'd like. I'd like to get this pr merged.

**Comment by ericclemmons** [comment]
@steveoh Are you https://www.npmjs.com/~steveoh?  I'll give you both `npm publish` and collaborator rights if you'd like!

**Comment by steveoh** [comment]
Yup that's me.

**Comment by ericclemmons** [comment]
@steveoh BAM!

```shell
$  npm owner ls
ericclemmons <eric@smarterspam.com>
steveoh <sgourley@utah.gov>    
```

**Comment by steveoh** [comment]
duplicate of #8

**Pull request closed without merging**
